language: node_js
node_js:
- '7'
branches:
  only:
  - master
addons:
  ssh_known_hosts: 104.154.171.198
before_script:
- npm install
script:
- ng build --prod
after_success:
- mkdir html
- mv *.* html
- mv -r assets html
- scp -rp html orbi0101@104.154.171.198:/var/www/html
before_install:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_38e477345159_key -iv $encrypted_38e477345159_iv -in depkey.ppk.enc -out depkey.ppk -d
- eval "$(ssh-agent -s)"
- chmod 600 depkey.ppk
- ssh-add depkey.ppk
