language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script:
- npm install
script:
- ng build --prod
addons:
  ssh_known_hosts: 104.154.171.198
before_deploy:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_38e477345159_key -iv $encrypted_38e477345159_iv -in deploykey.ppk.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
